[package]
name = "power-rules-daemon"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
dirs = "5.0"
notify = "6.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

